### ISSUE TITLE
nice-grpc-server-reflection fails typescript check and at runtime when using yarn berry

### ISSUE THREAD

**Issue by SoftMemes** [deeplay-io/nice-grpc#110]
First of all, thank you for all the work on nice-grpc. I'm evaluating it currently as the option for a future commercial project, and overall, it is indeed pretty nice!

I am using yarn 3.2 with workspaces, and when using pnp, or the pnmp node linker, the reflection addon fails as does not have a direct dependency on @grpc/grpc-js

```
Error: nice-grpc-server-reflection tried to access @grpc/grpc-js, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @grpc/grpc-js
Required by: nice-grpc-server-reflection@npm:1.0.9 (via [removed]/.yarn/cache/nice-grpc-server-reflection-npm-1.0.9-8e916f28db-8ae62f73d5.zip/node_modules/nice-grpc-server-reflection/lib/proto/grpc/reflection/v1alpha/)
```

Presumably this would be fixed by having a direct dependency on @grpc/grpc-js

**Comment by aikoven** [comment]
Thanks for the report.

Ideally, `nice-grpc-server-reflection` should not depend on `grpc-js`, but right now it uses legacy protobuf build with `google-protobuf`, which generates code that imports `@grpc/grpc-js`. In the future, we would move it to `ts-proto` or raw `protobufjs`.

In the meantime, I'll just add `@grpc/grpc-js` as a dependency as a workaround.

Please try these new versions:

```
 - nice-grpc@1.1.0
 - nice-grpc-server-reflection@1.0.10
```

**Comment by SoftMemes** [comment]
Works beautifully, many thanks!

**Comment by aikoven** [comment]
Great! Have fun with your project 🙂
