### ISSUE TITLE
Relative deadlines

### ISSUE THREAD

**Issue by nick-lehmann** [deeplay-io/nice-grpc#122]
I know that it is nitpicking, but would it be possible to define deadlines as a relative amount of miliseconds instead of an absolute date? Currently, the definition of the deadlines is slightly cumbersome
 
```ts
return this.client.listEntries(request,
    deadline: new Date(Date.now() + 1000),
})
```

For me, a deadline just specifies how much time I expect the gRPC server to handle the response, e.g., one second at max. Hence, it would be more convienent if the example above could be written as just

```ts
return this.client.listEntries(request,
    deadline: 1000,
})
```

Looking at the implementation of the deadline middleware, it subtracts the given deadline timestamp from the current one anyway.

```ts
const timer = setTimeout(() => {
    timedOut = true;
    abortController.abort();      
}, deadline.getTime() - Date.now());
```

It would be quite easy to support both ways. If the given deadline is a `number`, use it for the timeout right away. If it is a `Date` object, subtract the current timestamp. I am also willing to open a PR for this, if a maintainer approves this idea.

P.S. Very nice project, thank you ❤️

**Comment by aikoven** [comment]
Sure, go for it!
