### ISSUE TITLE
Opentelemetry support

### ISSUE THREAD

**Issue by ricofegh** [deeplay-io/nice-grpc#173]
@opentelemetry/instrumentation-grpc doesn't work for nice-grpc, because it patches methods right after `makeClientConstructor` invocation and it patches only methods passed via makeClientConstructor argument. Meanwhile, inside nice-grpc methods are appended to the instance after `makeClientConstructor` invocation. 
Do you have any plans to support opentelemetry out of the box?

**Comment by aikoven** [comment]
Yes, we have plans to make an official integration with OTel and even have it in the works right now. Expect it released within two weeks.

**Comment by aikoven** [comment]
OpenTelemetry support is [available](https://github.com/deeplay-io/nice-grpc/tree/master/packages/nice-grpc-opentelemetry) now!

📦 `nice-grpc-opentelemetry@0.1.1`
