### ISSUE TITLE
 EventEmitter memory leak in nice-grpc package

### ISSUE THREAD

**Issue by OmkarKirpan** [deeplay-io/nice-grpc#18]
While running test cases I'm getting MaxListenersExceededWarning in `cancel` test cases of **bidiStreaming.ts, clientStreaming.ts, serverStreaming.ts and unary.ts**

(node:23900) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 abort listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit

**Comment by aikoven** [comment]
Could you please share the test case?

**Comment by aikoven** [comment]
Oh, do you mean the tests inside this repo? If so, could you please show the console output?

**Comment by OmkarKirpan** [comment]
Yes, cancel test cases inside nice grpc package

**Comment by OmkarKirpan** [comment]
(node:23900) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 abort listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit

**Comment by aikoven** [comment]
On what OS and Node.js version are you running the tests? What exact command are you using to run them?

I don't see this warning in my setup, nor in GitHub Actions: https://github.com/deeplay-io/nice-grpc/runs/2961516869?check_suite_focus=true

Is there any sort of additional info, like a stack trace?

**Comment by aikoven** [comment]
I'm going to close this issue due to inactivity. Please feel free to reopen if needed.
