### ISSUE TITLE
native AbortController.abort() is always called when stream is ended

### ISSUE THREAD

**Issue by AVVS** [deeplay-io/nice-grpc#218]
Hi, @grpc/grpc-js always emits 'cancelled' event on 'close', which results in AbortController.abort being called each request. This, in turn, creates new DomException, which leads to stack trace capture and is extremely slow. One way to avoid it is to pass optional `reason` straight from the grpc. This should give a substantial boost in performance (I'm seeing about 10-15% throughput increase depending on the hardware)

**Comment by AVVS** [comment]
I've submitted a fix to @grpc/grpc-js for that, believe it has been release by now. That should sort the issue here

**Comment by aikoven** [comment]
I have added some tests for this in #229 and can confirm that updating `grpc-js` to 1.7.3 makes them all pass.

Thanks again!
