### ISSUE TITLE
nice-grpc-web@npm:2.0.0 doesn't provide google-protobuf (p5bd36), requested by @improbable-eng/grpc-web

### ISSUE THREAD

**Issue by rikbrown** [deeplay-io/nice-grpc#226]
Hi,

I'm getting the below warning after installing using `yarn`:

```
nice-grpc-web@npm:2.0.0 doesn't provide google-protobuf (p5bd36), requested by @improbable-eng/grpc-web
```

I installed following the instructions for nice-grpc-web + ts-proto, converting to yarn:
```
yarn add nice-grpc-web
yarn add protobufjs long
yarn add -D grpc-tools ts-proto
```

Manually adding `google-protobuf` doesn't seem to remove the warning either.

This doesn't seem to stop the package working, but wasn't sure if this is indicative of a problem with the package setup.

Thanks

**Comment by aikoven** [comment]
Hey, thanks for your report.

This is an issue with [`@improbable-eng/grpc-web`](https://github.com/improbable-eng/grpc-web) which lists `google-protobuf` in its `peerDependencies` without actually using it.

There's a PR fixing this: https://github.com/improbable-eng/grpc-web/pull/1068
