### ISSUE TITLE
Incompatibility with ts-proto@1.92.0 and higher 

### ISSUE THREAD

**Issue by skycrazyk** [deeplay-io/nice-grpc#26]
## Problem

All properties became incompatible with `never`.  

![image](https://user-images.githubusercontent.com/7424691/145667030-98464c6a-d585-4cd4-88ec-c59295a6f545.png)

my users.proto file

![image](https://user-images.githubusercontent.com/7424691/145667171-fcb8e17c-db75-4387-acde-21a47bb4212c.png)

## Reason

I spend a few hours trying to figure out why it's happens, and I finally find out that in ts-proto@1.92.0 changed a type of `fromPartial` argument

Diff compiled user.ts file ts-proto@1.91.0 (1) and 1.92.0 (2)

![image](https://user-images.githubusercontent.com/7424691/145667550-75294d3f-f964-4990-9414-98ec25379f94.png)

So now they use Exact generic 

![image](https://user-images.githubusercontent.com/7424691/145667715-06fe2fa0-1023-40ad-9d0c-5b8ae5b7110b.png)

And this works if we use`fromPartial` directly. But in file https://github.com/deeplay-io/nice-grpc/blob/master/packages/nice-grpc-web/src/service-definitions/ts-proto.ts#L35 used `Parameters` helper which somehow break `fromPartial`'s args definition 

type of fromPartial args before using Parameters

![image](https://user-images.githubusercontent.com/7424691/145668138-acc585b3-af37-4c42-95c7-cfdd147f0658.png)

after 

![image](https://user-images.githubusercontent.com/7424691/145668162-62e4c03a-d8b3-4537-bb44-85c3c5c4e4c0.png)

**Comment by aikoven** [comment]
Thanks for the report.

I'll try to fix it on the `nice-grpc` side first. I doubt that it is possible to preserve the Exact semantics though.

**Comment by aikoven** [comment]
Created an issue in `ts-proto` repo: https://github.com/stephenh/ts-proto/issues/454

**Comment by aikoven** [comment]
Starting with `ts-proto@1.97.0` you can use the `useExactTypes=false` option to switch back to old behavior.
