### ISSUE TITLE
Using gRPC-Web Developer Tools?

### ISSUE THREAD

**Issue by segfault16** [deeplay-io/nice-grpc#27]
Hi,

I was wondering if there was any way to make this nice package work with https://github.com/SafetyCulture/grpc-web-devtools?

**Comment by aikoven** [comment]
That would be nice to have, I'll look into this.

Alternatively, we could make a fork of `grpc-web-devtools` that integrates directly with `nice-grpc-web`.

**Comment by segfault16** [comment]
There's already a fork of grpc-web-devtools using interceptors because grpc-web-devtools can't be used together with interceptors, see https://github.com/SafetyCulture/grpc-web-devtools/pull/79.

**Comment by segfault16** [comment]
@aikoven Based on https://github.com/timostamm/protobuf-ts/issues/252 I had some initial success implementing a ClientMiddleware that posts similar message to the window :)

**Comment by aikoven** [comment]
Good to hear @segfault16! When you have a working repo, post a link to it and I will include it to the readme 🙂

**Comment by h3n4l** [comment]
Any update for this one?

**Comment by aikoven** [comment]
No updates from our side. PRs are welcome!

**Comment by segfault16** [comment]
@aikoven I've created a PR with an initial version.
