### ISSUE TITLE
Closing Streams from Client?

### ISSUE THREAD

**Issue by JakeCooper** [deeplay-io/nice-grpc#29]
I couldn't seem to figure out how to close a stream from the client, given it only returns an Async iterable :S

**Comment by aikoven** [comment]
There are two ways fitting different cases:

1. Use the `AbortSignal`
2. Use `break` in a `for await .. of` loop

**Comment by JakeCooper** [comment]
I've gone ahead and used the node abort controller but seem to be running into an issue where it can't seem to read property signal of undefined?

<img width="601" alt="CleanShot 2021-12-16 at 18 31 11@2x" src="https://user-images.githubusercontent.com/5499880/146479275-83397c77-ac06-407c-8643-35ca837cd480.png">

<img width="399" alt="CleanShot 2021-12-16 at 18 31 46@2x" src="https://user-images.githubusercontent.com/5499880/146479329-2d415841-f86a-4edf-846c-78ec920d6ff2.png">

I'm like 99% sure this is an implementation specific mess up but I've been tearing my head out for a few hours now over it. Any thoughts? Abort Signal seems to be valid here

**Comment by aikoven** [comment]
This is because you are losing `this` context of `abort` function after destructuring.

Try doing it like this instead:

```ts
const abortController = new AbortController();

const {signal} = abortController;

let stream = streamDeployLogs({containerId: deployment.containerId}, {signal});
setTimeout(() => {
  abortController.abort();
}, 2000)
```

**Comment by JakeCooper** [comment]
Buddy you're a fuckin' hero

If you turn on donations/send me your wallet address/whatever I'd love to send you something :D
