### ISSUE TITLE
FetchTransport is not a function

### ISSUE THREAD

**Issue by roboslone** [deeplay-io/nice-grpc#311]
I'm using `nice-grpc-web@3.0.0` and for some reason Vite refuses to import transports for me.
When importing from package:
```typescript
import { FetchTransport, WebsocketTransport } from 'nice-grpc-web'
```
```
Uncaught TypeError: FetchTransport is not a function
```

When importing explicitly (I probably shouldn't do that):
```typescript
import { FetchTransport } from 'nice-grpc-web/src/client/transports/fetch'
import { WebsocketTransport } from 'nice-grpc-web/src/client/transports/websocket'
```
```
Failed to resolve import "nice-grpc-web/src/client/transports/fetch" from "XXX.ts". Does the file exist?
```

When logging entire package contents:
```
import * as grpc from 'nice-grpc-web'
console.info(grpc)
```
I can see that both `FetchTransport` and `WebsocketTransport` are indeed `undefined`.

I've tried removing `node_modules` completely and running `pnpm i`, that doesn't help.

<img width="345" alt="Screenshot 2023-03-08 at 11 38 03" src="https://user-images.githubusercontent.com/1941275/223663973-16622c96-1221-4ab8-8fd1-9084086088fc.png">

**Comment by roboslone** [comment]
I've checked `node_modules` and the code seems to be in the right place:
```
% stat node_modules/nice-grpc-web/src/client/transports/fetch.ts
  File: node_modules/nice-grpc-web/src/client/transports/fetch.ts
  Size: 3615      	Blocks: 8          IO Block: 4096   regular file
  ...
```

**Comment by roboslone** [comment]
I've also tried to wipe `pnpm` cache and perform a fresh install, got the same result.

**Comment by aikoven** [comment]
Thank you for you report.

At runtime, files are imported from `node_modules/nice-grpc-web/lib/` dir. Could you please check that transport modules exist in that directory?

**Comment by roboslone** [comment]
@aikoven yeah, I did check, everything seems okay:
```
# node_modules/nice-grpc-web/lib/client/transports
% ls
fetch.d.ts  fetch.js  fetch.js.map  websocket.d.ts  websocket.js  websocket.js.map
```

**Comment by roboslone** [comment]
I also tried explicitly importing from `lib`:
```typescript
import { FetchTransport } from 'nice-grpc-web/lib/client/transports/fetch'
import { WebsocketTransport } from 'nice-grpc-web/lib/client/transports/websocket'
```
Didn't work.

**Comment by roboslone** [comment]
OMG, so sorry. I forgot to run `pnpm i` in dependent library (which provides custom client factory and was still using v2). Everything works as expected now, sorry for troubling.
