### ISSUE TITLE
Server streaming error handling

### ISSUE THREAD

**Issue by markusa380** [deeplay-io/nice-grpc#317]
I am unable to correctly handle an error in a server streaming method.

```
    try {
      for await (const value of ...) {
        ...
      }
    } catch (err) {
      console.log(err);
    }
```
results in the following message:
```
TypeError: The iterator does not provide a 'throw' method.
    at Object.<anonymous> (createServerStreamingMethod.js:56:13)
    at Generator.throw (<anonymous>)
    at resume (AsyncGenerator.js:6:1)
    at AsyncGenerator.js:17:1
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:25619:33)
    at _ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at zone.js:1275:36
    at _ZoneDelegate.invokeTask (zone.js:406:31)
```

Maybe there is a solution but the documentation doesn't show any, and `AsyncIterable` is not well documented either.

Excerpt from my `package-lock.json`:

```
        "nice-grpc": "1.2.2",
        "nice-grpc-common": "1.1.0",
        "nice-grpc-web": "2.0.0",
```

**Comment by aikoven** [comment]
Thank you for your report. Does your code use `nice-grpc` or `nice-grpc-web`?

As I can see your versions of libraries are pretty outdated. Have you tried to update?

**Comment by markusa380** [comment]
I think we are using `nice-grpc-web`. It's a large corporate project so I cannot simply update probably. I will try however. In parallel, any ideas if there's a fix/workaround?

**Comment by aikoven** [comment]
It's hard to propose a fix without knowing the reason for an error. Are you using any client middleware?

**Comment by markusa380** [comment]
Hey @aikoven, just to let you know, updating the versions did fix the issue.

**Comment by aikoven** [comment]
Glad to hear! Good luck.
