### ISSUE TITLE
Alternative to NodeHttpTransport in nice-grpc-web@3.0.0

### ISSUE THREAD

**Issue by awesomenode** [deeplay-io/nice-grpc#322]
Hi,

First of all thanks for this great package!

I used previous versions to send grpc-web messages from nodejs. I could achieve this using [NodeHttpTransport](https://github.com/improbable-eng/grpc-web/blob/master/client/grpc-web-node-http-transport/src/index.ts) as transport, however it is not possible anymore as it is stated in the changelog.

Do you have any suggestion how I could have the same functionality in the new version?

Thanks

**Comment by aikoven** [comment]
Hey,

Are you using NodeJS version older than 16?

`nice-grpc-web` works with NodeJS 18 out of the box, and for NodeJS 16 it can be made to work with a few tweaks.

**Comment by awesomenode** [comment]
I am developing a VS Code extension, as far as I see VS Code uses NodeJS 16.14.2

**Comment by aikoven** [comment]
I see. Unfortunately it is too old even for the [undici fetch implementation](https://undici.nodejs.org/#/?id=undicifetchinput-init-promise).

We need do add a new transport based on NodeJS `http` / `https` modules.

**Comment by aikoven** [comment]
Please try the new `NodeHttpTransport` from 📦 `nice-grpc-web@3.2.0`
