### ISSUE TITLE
All of my requests are staying on pending state 

### ISSUE THREAD

**Issue by delhamza** [deeplay-io/nice-grpc#328]
Can someone tell me how to solve this issue ?

**Comment by aikoven** [comment]
This issue is not actionable unless you provide more details.

**Comment by delhamza** [comment]
I make requests from my front but the moment when i use streams i can't abort the stream, neither catch the end of it and abort.

**Comment by aikoven** [comment]
It is still not clear. Can you make a reproduction example?

**Comment by delhamza** [comment]
`const useStream = <TReply>() => {
  const [currentStream] = React.useState<AsyncIterable<TReply>>();

  const { logout } = useAuth0();

  const handleStream = React.useCallback(async function* (
    stream: AsyncIterable<TReply>
  ) {
    try {
      for await (const reply of stream) {
        console.log("return from stream", reply);

        yield reply;
        if (reply && Object.keys(reply).length !== 0) {
          break;
        }
      }
    } catch (error) {
      console.debug("Cancelling stream due to component unmounting", error);
      logout({
        logoutParams: { returnTo: window.location.origin + "?logout=true" },
      });
    }
  },
  []);`  I'm passing the stream request to this hooks but i can't cancel it, neither catch when it's done

**Comment by aikoven** [comment]
When you call an async generator (`async function*`), it won't execute its code, it will only create and return an `AsyncIterable`, which must be iterated for the code to be executed.

Try to use a normal async function instead, and remove the `yield reply`.

**Comment by delhamza** [comment]
Yes But to handle the stream Like this :
`for await (const value of handleStream(stream)) {
           // get the reply 
      }`
I'm forced to return an AsyncGenerator

**Comment by aikoven** [comment]
No, you're not. You can use `for await` in a regular async function.

**Comment by delhamza** [comment]
Even after updating the code the stream get blocked in a pending after a several requests, do you think it comes from the backend configuration ?

**Comment by aikoven** [comment]
You can use a console client like [grpcurl](https://github.com/fullstorydev/grpcurl) to probe your server methods. If the same situation happens with grpcurl, it would mean that the problem is somewhere on the server.

**Comment by aikoven** [comment]
You can use `AbortSignal` to cancel the call. See https://github.com/deeplay-io/nice-grpc/tree/master/packages/nice-grpc-web#cancelling-calls
