### ISSUE TITLE
I am planning to add CONTRIBUTING.md to this library

### ISSUE THREAD

**Issue by anmol242** [deeplay-io/nice-grpc#422]
Hello everyone, and thank you for creating this fantastic library. After seeing that my organization was using this fantastic library, I suggested it to many of my friends. I recently made a contribution to this library few months back. I noticed that this repo lacks a 'CONTRIBUTING.md' file. I'm taking the initiative to commit one so that future contributors will benefit if they choose to contribute to this library. I'll fill in the details based on my understanding or how I setup up this lib in my local. So, if any information is missing or I mention something incorrectly, I will require the assistance of a expert 😄 .

P.S. Special thanks to @aikoven 🚀 . I've seen that he actively responds to everyone who raises an issue or a PR in this repo 😃 .

**Comment by aikoven** [comment]
I'm glad you liked it 🙂

Sure, I'd love to see that contribution from you!
