### ISSUE TITLE
Error when making a request

### ISSUE THREAD

**Issue by Nikjee** [deeplay-io/nice-grpc#425]
When making a request im getting this error, can it be a problem with content type application/grpc-web+proto? Currently im using native grpc-web lib and its content type response is application/grpc-web-text

![image](https://github.com/deeplay-io/nice-grpc/assets/35499368/9d62fa95-8861-4df6-b3fc-acbbad94ed30)

Here is a code

```ts
import { createChannel, createClient, Metadata } from 'nice-grpc-web'
import { CatalogProductServiceDefinition } from './product'
import type { CatalogProductServiceClient } from './product'

const channel = createChannel('http://localhost:8088')

const client: CatalogProductServiceClient = createClient(
  CatalogProductServiceDefinition,
  channel
)

export const request = () => {
  client
    .listCatalogProduct({
      filter: {
        items: [
          {
            fieldName: '',
            operand: '',
            or: undefined,
            value: '',
          },
        ],
      },
      sort: { exp: 'asc', name: 'p.product_name' },
      pagination: { cnt: 0, limit: 1000, page: 1, pages: 0 },
    })
    .then((res) => console.log('Response', res))
    .catch((err) => console.log('Error', err))
}
```

EDIT: 
Looks like the problem is behind proxy, i tried using envoy example from grpc-web and it works, our backend apparently doesn't use proxy

**Comment by aikoven** [comment]
Hey @Nikjee,

Is the issue resolved?

**Comment by Nikjee** [comment]
> Hey @Nikjee,
> 
> Is the issue resolved?

Nope, our backend uses http server and in its handler being passed grpc server

**Comment by Nikjee** [comment]
@aikoven I came to another problem, when create a request second option "Call context" isn't optional for me

**Comment by aikoven** [comment]
I'm sorry but it's not clear what problem do you have. You mention very different issues and solutions that aren't relevant to each other.

I'm going to close this issue. If you still have any problems, please open new issues, one per topic.

If you need general help in figuring out what's happening, please use Discussions.
