### ISSUE TITLE
Is there a way to provide credentials with WebsocketTransport?

### ISSUE THREAD

**Issue by roboslone** [deeplay-io/nice-grpc#448]
Currently we're using `FetchTransport` with `{ credentials: 'include' }`, which sends session cookie to the server. Is there a way to get the same behaviour with `WebsocketTransport`?

**Comment by roboslone** [comment]
@aikoven could you help me with this one?

**Comment by aikoven** [comment]
Hey @roboslone 

I did a small research and I don't think that it is possible with the WebSocket API.

I may be wrong though. If you find a way — PRs are welcome!

**Comment by roboslone** [comment]
Looks like the problem is JS doesn't have access to secure cookies, so they can't be added to metadata. Manually created metadata can in fact be sent to server, so it seems there's nothing wrong with transport itself.
