### ISSUE TITLE
WebsocketTransport fails in Safari

### ISSUE THREAD

**Issue by roboslone** [deeplay-io/nice-grpc#449]
Safari Version 16.6 (18615.3.12.11.2)

Most requests end with this error:
```
The operation couldn’t be completed. Protocol error
Transport error: WebSocket closed with code 1006
```
It occurs on unary requests and on server streaming requests.

SO suggests this is abnormal connection termination initiated by browser.
Is there a way to get a better error here?

**Comment by aikoven** [comment]
Hey @roboslone 

The only way I know to get more info about error is examining the request in browser dev tools. Browsers usually pass very little info to JS errors due to security reasons.

**Comment by roboslone** [comment]
I don't remember what I did, but at the end I got wss working in both Safari & Chrome.
¯\_(ツ)_/¯
