### ISSUE TITLE
TS compilation fails on `Long`

### ISSUE THREAD

**Issue by GaikwadPratik** [deeplay-io/nice-grpc#5]
Hi,

Nice project. I got it working mostly. I had some compiler errors fr `protobufjs/minimum`, so I had to update version to 6. Now  after generating TS files from Proto, I'm getting below error:

```
lib/proto/google/protobuf/empty.ts:78:5 - error TS2367: This condition will always return 'true' since the types 'Constructor<Long>' and '{ default: LongConstructor; prototype: Long; MAX_UNSIGNED_VALUE: Long; MAX_VALUE: Long; MIN_VALUE: Long; NEG_ONE: Long; ONE: Long; ... 11 more ...; fromValue(val: string | ... 2 more ... | { ...; }): Long; }' have no overlap.

78 if (util.Long !== Long) {
       ~~~~~~~~~~~~~~~~~~
```

Version information

```
Typescript version: 4.2.4
NodeJS: v10.19.0
```

This error is repeated in other TS files which are generated from proto files as well. Any idea how can I fix this?

Let me know if you need anymore information from my side.

**Comment by aikoven** [comment]
This looks like an issue with [ts-proto](https://github.com/stephenh/ts-proto).

My guess is that you have multiple versions of `long` package installed. I recommend adding `long` to the list of dependencies of your app, then checking `yarn.lock` or `package-lock.json` for duplicates of `long`.

**Comment by reolat** [comment]
Hello!
Have a look at the compiled .ts file (at the bottom):

```
// If you get a compile-error about 'Constructor<Long> and ... have no overlap',
// add '--ts_proto_opt=esModuleInterop=true' as a flag when calling 'protoc'.
if (util.Long !== Long) {
  util.Long = Long as any;
  configure();
}
```

You have two approaches to fix this issue:
* invoke protoc with the esModuleInterop=true flag
* disable esModuleInterop in your tsconfig

**Comment by GaikwadPratik** [comment]
@reolat,

Thank you a lot. This nudges me back to my good old habit of reading things more carefully. Closing this
