### ISSUE TITLE
How to get original long value ? 

### ISSUE THREAD

**Issue by czy88840616** [deeplay-io/nice-grpc#575]
Hi

Is there any approach to retain the original long value? I require the original long value and to convert it into a string.
![image](https://github.com/deeplay-io/nice-grpc/assets/418820/da91cf8e-3d5e-490d-85c7-97f84684b1b3)

Add a private property ?
![image](https://github.com/deeplay-io/nice-grpc/assets/418820/4d7d618d-4fa4-4fc1-bf8b-5b0564f25a91)

**Comment by czy88840616** [comment]
Okay, I found it generated by grpc-tools, not nice-grpc.

**Comment by aikoven** [comment]
Hey

This is configured in `ts-proto` using `--ts_proto_opt=forceLong=long`.

See all options here: https://github.com/stephenh/ts-proto?tab=readme-ov-file#supported-options

**Comment by czy88840616** [comment]
Thank you for your help.
