### ISSUE TITLE
Can we make a version of javascript style readme?

### ISSUE THREAD

**Issue by wang-xiaowu** [deeplay-io/nice-grpc#588]
Can we make a version of javascript style readme?
```[tasklist]
### Tasks
```

**Comment by aikoven** [comment]
Hey @wang-xiaowu!

Can you elaborate on why is it needed?

It should be possible to use the TypeScript readme for JavaScript development, just remove the types. There are tools that can help with that, for example https://transform.tools/typescript-to-javascript

Maintaining another version of documentation looks like a burden to me, so it needs justification.

**Comment by wang-xiaowu** [comment]
you're right.
using tool is practical for me.
