### ISSUE TITLE
Automatically wrap partials

### ISSUE THREAD

**Issue by reolat** [deeplay-io/nice-grpc#6]
Currently, when I return a partial answer from my serviceImplementation, the server throws an error.
With a .proto like this:
```proto
message User {
  int32 id = 1;
  string username = 2;
  string email = 3;
  string password = 4;
}

message GetUserByIdRequest {
  int32 id = 1;
}

message GetUserByIdResponse {
  User user = 1;
}

service SAuth {
  rpc getUserById(GetUserByIdRequest) returns (GetUserByIdResponse);
}
```

I would like to be able to return a user but without the password field.

```ts
    async getUserById(req: GetUserByIdRequest): Promise<GetUserByIdResponse> {
        //get data from db, delete / filter the password field
        return {user: {id: req.id, username: "felix", email: "felix@wildworld.at"} } as GetUserByIdResponse
    }
```

This code throws the following error:
`panic: rpc error: code = Internal desc = The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined`
(I tracked it down, it is thrown by the @grpc/grpc-js library)

One possible solution would be to manually wrap the object into the generated GetUserByIdResponse.fromPartial method like this:

```ts
    async getUserById(req: GetUserByIdRequest): Promise<GetUserByIdResponse> {
        return GetUserByIdResponse.fromPartial({user: {id: req.id, username: "felix", email: "felix@wildworld.at"}}) as GetUserByIdResponse
    }
```

While this is a good workaround for this issue, it would be nice if the library could handle this case and automatically and wrap the response with this function.
The same issue also applies to sending partials from the client, could this library also wrap fromPartial here?

**Comment by aikoven** [comment]
Yes, I think this would be nice to have, but right now it is not straightforward. 

Currently the correct way is to use `fromPartial`.

The current integration with `ts-proto` works because `nice-grpc` understands the service definition format of `grpc-js`, which `ts-proto` is able to output. But I have plans to make a better and more generic service definition output from `ts-proto`, which would allow for more tight integration between `nice-grpc` and `ts-proto`, and hopefully make this feature possible.

**Comment by aikoven** [comment]
This became possible after generic service definitions [were added](https://github.com/stephenh/ts-proto/pull/316) to `ts-proto`, and now is supported by `nice-grpc@1.0.0`: https://github.com/deeplay-io/nice-grpc/pull/14
