### ISSUE TITLE
Server-side streaming thrown errors are not propagating to client

### ISSUE THREAD

**Issue by davidfiala** [deeplay-io/nice-grpc#607]
Using nice-grpc and/or nice-grpc-web as both the client and server:

```
"nice-grpc": "2.1.8",
"nice-grpc-common": "2.0.2",
```

with grpc-js pinned to 1.10.6 - which is admittedly not known to be supported (https://github.com/deeplay-io/nice-grpc/issues/555). the bug could be related to this.

trimmed example:

```
  async *myRpc(
    request: r.MyRequest,
    context: CallContext,
  ): r.ServerStreamingMethodResult<r.MyResponse> {
    console.error('okok');
    throw new ServerError(Status.ALREADY_EXISTS, 'blahlbhahala');
    // same bug if I yield* to something that throws
  }
```

```
const stream = client.myRpc({ });
for await ( const msg of stream ) { console.log(msg); }
catch(e) { console.error('error', e); }
finally { console.log('got finally'); }
```

I've observed that the server does log the `okok` but silently does nothing on the throw. The client will async iterate on server responses, and if any are sent it will receive them up until the throw. Once a server throw occurs, it seems like the client neither gets a `catch` nor `finally`. Just hangs.

**Comment by aikoven** [comment]
It seems very likely to me to be caused by grpc-js 1.10.

The failing tests catch this situation here: https://github.com/deeplay-io/nice-grpc/actions/runs/9346639886/job/25721924757#step:7:573
