### ISSUE TITLE
Cannot createServer with Custom Context in nice-grpc Package

### ISSUE THREAD

**Issue by samasri** [deeplay-io/nice-grpc#73]
I see that `Server` can take a special `Context` ([here](https://github.com/deeplay-io/nice-grpc/blob/master/packages/nice-grpc/src/server/Server.ts#L20)), however, I could not figure out how to create a server with that context.

```typescript
import { Server, createContext } from 'nice-grpc';

type CustomType = {
  specialField: string;
}
const server: Server<CustomType> = createServer(); // this fails with: `Type 'Server<{}>' is not assignable to type 'Server<CustomType>'`
const server: Server<CustomType> = createServer<CustomType>(); // I would assume that's how it should be done, but createContext does not take generics
```

Taking a closer look at the source code, I can see that [createServerWithMiddleware function](https://github.com/deeplay-io/nice-grpc/blob/master/packages/nice-grpc/src/server/Server.ts#L60) takes a generic, however, this generic can never be accessed from the API user. So I think this can be solved by adding a generic type to `createServerWithMiddleware` that would get passed on to `createServerWithMiddleware`

**Comment by aikoven** [comment]
The only way for extra fields to actually appear in the context is through middleware. `createServer` creates a server with no middleware, so this is the correct behavior. Moreover, by just specifying a generic parameter, you won't get an actual value in the context — there must be some code that sets the value in runtime.

See the [authentication middleware example](https://github.com/deeplay-io/nice-grpc/tree/master/packages/nice-grpc#example-authentication) on how to extend the context.

**Comment by samasri** [comment]
Got it, thanks!
